[[constraint]]
    name = "git.apache.org/thrift.git"
    branch = "0.12.0"

[[constraint]]
    name = "github.com/pkg/errors"
    revision = "e881fd58d78e04cf6d0de1217f8707c8cc2249bc"

[[constraint]]
    name = "github.com/samuel/go-zookeeper"
    revision = "471cd4e61d7a78ece1791fa5faa0345dc8c7d5a5"

[[constraint]]
    name = "github.com/stretchr/testify"
    version = "1.2.0"

